[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    #{ id = "RUSTSEC-2022-0092", reason = "askalono always provides valid utf-8 files from a cache, this is not relevant" },
]

[bans]
highlight = "all"
#multiple-versions = "warn"
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true

[licenses]
version = 2
unused-allowed-license = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "Zlib",
    "ISC",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
#    "MPL-2.0",
#    "OpenSSL",
#    "CC0-1.0",
#    "BSD-2-Clause",
]
confidence-threshold = 1.0

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-registry = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]
unknown-git = "deny"
allow-git = []
[sources.allow-org]
github = [ "ifeisier" ]
gitlab = []
bitbucket = []