[package]
name = "internal_core"
version = "0.1.0"
license = "MIT"
edition.workspace = true
description = "业务核心逻辑 (Domain + Application)"

[dependencies]
tokio = {workspace = true}
anyhow = {workspace = true}
log = {workspace = true}
rumqttc = {workspace = true}
crossbeam = {workspace = true}
