[package]
name = "internal_shared"
version = "0.1.0"
edition.workspace = true
description = "通用工具库 (日志、配置加载等)"

[dependencies]
anyhow = {workspace = true}
log = {workspace = true}
flexi_logger = {workspace = true}
